PackageInfo.g
doc/z-chap1.xml

[The old website](http://www-groups.mcs.st-andrews.ac.uk/~jamesm/digraphs.php) is changed everwhere in the package to [the new website](http://gap-packages.github.io/Digraphs/).

Use new URLs

---

doc/digraph.xml

This takes care of warnings about SetDigraphEdgeLabels being defined
more than once.

Add labels to SetDigraphEdgeLabels operations

---

doc/oper.xml
gap/oper.gi
tst/standard/oper.tst
tst/testinstall.tst

Previously, OnDigraphs for a digraph and a transformation mistakenly removed
all multiple edges of the resultant digraph. This commit fixes OnDigraphs.

Fix Issue #17 (OnDigraphs)

---

doc/attr.xml
gap/attr.gi
gap/digraph.gi
gap/oper.gd
gap/oper.gi
tst/extreme/oper.tst
tst/standard/oper.tst

`OutNeighboursCopy` is renamed to `OutNeighboursMutableCopy`.
`InNeighboursMutableCopy` is added.
Semigroups has one use of `OutNeighboursCopy`, and I've made a PR to change that too.

(Out/In)NeighboursMutableCopy

---

PackageInfo.g

For packages redistributed with GAP, the status should be one of accepted/submitted/deposited.

Updated status

---

doc/digraph.xml
gap/digraph.gi
tst/standard/digraph.tst
tst/testinstall.tst

This resolves issue #42. It fixes the bug that `AsDigraph(f, n)` returns a malformed digraph in the case that the transformation `f` does not actually define a transformation on `[1 .. n]`. After this PR, `AsDigraph(f, n)` returns `fail` in this case.

fix: AsDigraph for a transformation and an integer

---

doc/attr.xml
doc/oper.xml
doc/prop.xml
doc/z-chap2.xml
doc/z-chap3.xml
gap/attr.gd
gap/attr.gi
gap/oper.gd
gap/oper.gi
gap/prop.gd
gap/prop.gi
src/digraphs.c
tst/standard/attr.tst
tst/standard/oper.tst
tst/standard/prop.tst

The package already includes the property `IsUndirectedTree`, which decides whether a digraph is a tree in the usual graph-theoretic sense (symmetric, connected, no cycles).
This PR adds several new features related to undirected trees:
* property`IsUndirectedForest`: an undirected forest is a disjoint union of undirected trees.
* attributes `UndirectedSpanningTree` and `UndirectedSpanningForest`: spanning tree has the usual sense, and a spanning forest is a subdigraph that is a forest and is maximal (with respect to containment of subdigraphs) with this property. This later attribute is the most important one for my purposes. Every digraph has a spanning forest (which may be an empty digraph); not every digraph has a spanning tree.
* operations `IsUndirectedSpanningTree` and …

Introduce methods for undirected spanning trees and forests

---

doc/attr.xml
doc/bliss.xml
doc/grahom.xml
doc/prop.xml
doc/z-appA.xml
doc/z-chap6.xml
gap/bliss.gd
gap/bliss.gi
gap/grahom.gd
gap/grahom.gi
gap/utils.gd
gap/utils.gi
src/digraphs.c
tst/standard/bliss.tst
tst/standard/grahom.tst

This PR adds support for isomorphism testing, and isomorphism finding, for *coloured* digraphs.
---
Previously in the Digraphs package... you could ask for the automorphism group of a coloured digraph without multiple edges (i.e. the subgroup of the automorphism of the digraph consisting of those elements that preserve the colouring), and you could ask for the canonical labelling of a coloured digraph without multiple edges.
I've now added similar support for coloured digraphs to the operations `IsIsomorphicDigraph` and `IsomorphismDigraphs`, for testing whether two coloured digraphs without multiple edges are isomorphic as coloured digraphs (i.e. whether there exists an isomorphism between the digraphs that respects the colourings of the vertices).
In addition to these new features, I've …

Improve user-facing isomorphism and canonical labelling functions, especially with colourings

---

src/digraphs.c
tst/testinstall.tst

This PR resolves Issue #55.
The problem was in line 864. The ADDR_OBJ macro was used on an
entry of the out-neighbours, without the guarantee that the entry
was a plain list. Thus, when given a range, this caused a seg fault.
This commit fixes this issue by using ELM_LIST(nbs, k) instead of
ADDR_OBJ(nbs)[k].
I also changed line 782 to behave like the other functions in the file.

Fix bug in FuncDIGRAPH_TOPO_SORT

---

src/digraphs.c
tst/testinstall.tst

This PR fixes a (probably long standing) bug in the kernel function `FuncIS_ANTISYMMETRIC_DIGRAPH` which assumed incorrectly that a variable was a plain list. 
This resolves Issue #52 and is the cause of the segmentation fault on travis for PR #51.

Fix IsAntisymmetricDigraph

---

doc/attr.xml
gap/oper.gd
gap/oper.gi
tst/standard/oper.tst

We've got `OutNeighboursMutableCopy`, `InNeighboursMutableCopy`, and `AdjacencyMatrixMutableCopy`, so I thought I should add `BooleanAdjacencyMatrixMutableCopy`. Julius should be able to make use of it in PR #57.

Add BooleanAdjacencyMatrixMutableCopy

---

gap/cliques.gi
tst/standard/cliques.tst

Previously the error referred to the fourth argument <hook>, when it
should be the second argument.

cliques: fix error message

---

doc/grahom.xml
gap/grahom.gi
tst/standard/grahom.tst

Currently, the one-argument version of `DigraphColouring` returns a colouring for a digraph, even if it has loops. This was inconsistent, and became issue #62.
This commit resolves issue #62.

Fix DigraphColouring to return fail for digraphs with loops (Issue #62)

---

src/digraphs.c

Note that GAP always overrides these values anyway. And right now I am working on a patch to remove them in GAP, which would arrive in GAP 4.9. To be more precise, I am not removing but moving them to another struct, in order to not expose this internal implementation detail needlessly to kernel extensions.
The one drawback of this I see is that it might trigger some warnings when compiling Digraph.

Don't set StructInitInfo members filename and isGapRootRelative

---

doc/attr.xml
doc/prop.xml
doc/z-chap4.xml
doc/z-chap5.xml
gap/attr.gd
gap/attr.gi
gap/prop.gd
gap/prop.gi
tst/standard/attr.tst
tst/standard/prop.tst

This PR adds two features: the ability to compute `ArticulationPoints` and as a consequence check if a digraph is biconnected. This uses a pretty straightforward depth first search originally by Tarjan.

attr: add ArticulationPoints and IsBiconnectedDigraph

---

doc/attr.xml
doc/oper.xml
doc/z-chap4.xml
doc/z-chap5.xml

In particular, 
1. fixed some things pointed out by `DIGRAPHS_CheckManualConsistency`
2. removed the two sections for partial orders which each only contained a single man section (these are redeployed elsewhere)
3. move the doc for `DigraphBicomponents` to the same section as the connected components.

Fix some anomalies in the doc

---

doc/display.xml
gap/display.gd
gap/display.gi
tst/standard/display.tst

This commit changes `DotDigraph` from a mutable attribute to an attribute,
and introduces `DotVertexLabelledDigraph`. I don't know why `DotDigraph` was a mutable
attribute since it was never used as such. I guess the original intention was that this could be recomputed after something about the digraph changed, but this was not implemented and so it makes more sense if it is an attribute. Since vertex labels can change `DotVertexLabelledDigraph` must be an operation.

Add DotVertexLabelledDigraph

---

doc/cliques.xml
doc/z-chap8.xml
gap/attr.gi
gap/cliques.gd
gap/cliques.gi
tst/standard/attr.tst
tst/standard/cliques.tst
tst/standard/grahom.tst
tst/standard/oper.tst

This PR adds the attribute `CliqueNumber` and uses it to improve `ChromaticNumber`. Several further minor modifications are made to improve the performance of `ChromaticNumber`, these include 
* sorting the connected components by size from smallest to largest, since colouring smaller digraphs is quicker than larger ones, and information about the colourings of the smaller components can be used to determine the overall chromatic number more quickly
* using `DigraphColouring` to obtain an upper bound for the chromatic number
* only trying to colour the digraph with a number of colours between the clique number plus one, and the number of colours used by `DigraphColouring` minus 1, instead of all values from `3` to the number of vertices minus 1
* using the chromatic number of smaller …

Add CliqueNumber and use it to improve ChromaticNumber

---

doc/digraph.xml
doc/z-chap2.xml
doc/z-chap4.xml
gap/digraph.gd
gap/digraph.gi
tst/standard/digraph.tst

Namely, `GroupOfCayleyDigraph`, `SemigroupOfCayleyDigraph`,
and `GeneratorsOfCayleyDigraph`, so that the digraph output by
`CayleyDigraph` can recover the semigroup and generating set
used to create the digraph.

Add more attributes for Cayley digraphs

---

Makefile.am
src/homos.c
src/homos.h

This PR replaces the function used by the macro`COUNT_TRUES_BLOCK` with a compiler intrinsic when compiling with GCC or clang.

kernel: use compiler intrinsic popcnt

---

gap/digraph.gi
tst/standard/digraph.tst
tst/testinstall.tst

This PR resolves issue #81 
A segfault would happen if you called `Digraph` on a list with holes. We weren't checking for this. I've added `IsDenseList` to the filters for digraph creation methods, where appropriate. I've made it more robust in another way too.

Fix issue 81

---

doc/digraph.xml
gap/digraph.gd
gap/digraph.gi
tst/standard/digraph.tst

This function returns the canonical digraph formed by applying
`CanonicalDigraphLabelling` to the input digraph.

CanonicalDigraph: Add the function CanonicalDigraph with doc & tests

---

gap/attr.gi
gap/digraph.gd
gap/digraph.gi
src/digraphs.c
tst/testinstall.tst

In this PR, I change the names of the record components of digraphs to match their attribute names. eg `nrvertices -> DigraphNrVertices`. This change makes the code nicer, and combined with a change to how we objectify digraphs, it leads to reduced memory usage. Previously, if you had a mutable list of out-neighbours, and you called `Digraph` on that list, then the record components `!.OutNeighbours` and `!.nbs` were *not* identical objects, and hence we were using twice as much memory as necessary. There is now just the one copy.
I've also changed `DigraphType` to include the filter `HasDigraphNrVertices`, since every digraph does have its number of vertices. If you look at the documentation in GAP for `ObjectifyWithAttributes`, you can see why including this filter would be desirable in …

Change the way that digraphs are objectified

---

gap/attr.gi
tst/testinstall.tst

A very simple change.  Previously `DigraphSymmetricClosure(EmptyDigraph(0));` produced an error.

Enable DigraphSymmetricClosure for digraphs with no vertices

---

doc/isomorph.xml
gap/isomorph.gd
gap/isomorph.gi
tst/standard/isomorph.tst

This operation takes a digraph and a permutation and returns true if the
permutation is an automorphism of the digraph. See also #105.

add method IsDigraphAutomorphism

---

gap/isomorph.gi
tst/testinstall.tst

It seems that NautyTracesInterface does not handle graphs with 0 vertices, and so we put a special case for this into `isomorph.gi`.

Resolve Issue #114

---

doc/grahom.xml

This PR adds (and corrects) the doc for `HomomorphismDigraphsFinder`,
where previously only 9 of the 11 arguments were documented.

Resolve issue #112

---

src/homos.c
tst/standard/grahom.tst

This PR resolves Issue #111, which was caused by orbit representatives in the homomorphism finding code being chosen to the the least element in any orbit, and only considering the image values of the homomorphism from among those orbit representatives. If the image was restricted to values which were not orbit representatives (i.e. that were not the least point in their orbits), as in Issue #111, then this could result in no homomorphism being found, when a homomorphism exists.

Fix issue #111

---

doc/grahom.xml
doc/isomorph.xml
doc/z-chap6.xml
gap/grahom.gd
gap/grahom.gi
gap/isomorph.gd
gap/isomorph.gi
tst/standard/grahom.tst
tst/standard/isomorph.tst

This PR adds new operations `IsDigraphHomomorphism`, `IsDigraphIsomorphism`, `IsDigraphMonomorphism`, `IsDigraphEpimorphism`, and `IsDigraphEndomorphism`. Also refactors `IsDigraphAutomorphism` and links the doc for `IsDigraphAutomorphism` into the manual for the first time. The arguments of any of these operations are digraph (or digraphs) and a perm or transformation. 
This breaks backwards compatibility with `IsDigraphAutomorphism`, which previously returned `true` for permutations that did not fix non-vertices. With this PR, the `IsDigraphAutomorphism` will return `true` if and only if the permutation belongs to the automorphism group, or the permutation defined by the transformation does.

Add IsDigraphHomomorphism and related operations

---

doc/display.xml
gap/display.gi
tst/standard/display.tst

I recently found myself wanting to use a different GraphViz renderer for `Splash`, so I added this option. Might be useful for others.

Make Graphviz engine configurable

---

doc/display.xml
doc/prop.xml
doc/z-chap5.xml
doc/z-chap9.xml
gap/display.gd
gap/display.gi
gap/prop.gd
tst/standard/display.tst
tst/standard/prop.tst

This commit also adds the property `IsPreorderDigraph` and its synonym `IsQuasiorderDigraph`. A preorder is a reflexive and transitive relation. It need not be anti-symmetric and thus can have strongly connected components containing multiple vertices. The components will be complete subdigraphs (due to reflexivity) and I chose to avoid drawing these edges and merge all these vertices. Essentially this is drawing the quotient digraph (quotienting by strongly connected components). For both preorders and partial orders these dot methods avoid drawing loops and edges implied by transitivity
(i.e. don't draw [a,c] if there are edges [a,b] and [b,c]).
The methods added are:
`IsPreorderDigraph`
`IsQuasiorderDigraph`
`DotPartialOrderDigraph`
`DotPreorderDigraph`
`DotQuasiorderDigraph`

display: add dot methods for preorder and partial order digraphs

---

gap/io.gi

The former is an undocumented internal low-level function (and as far as I
can tell, it has little reason to exist, other than historical). Much better
to use the documented high level counterpart.

Replace LEN_LIST by Length

---

src/homos.h

This PR removes `#include <x86intrin.h>` from `src/homos.h` which may be unnecessary. If the CI tests pass, then I propose to merge this PR. This works on my computer using Clang.

homos.h: fix Issue #147 (remove x86intrin.h)

---

doc/digraphs.bib
doc/grahom.xml
doc/prop.xml
doc/z-appA.xml
doc/z-chap6.xml
gap/attr.gi
gap/grahom.gd
gap/grahom.gi
tst/standard/attr.tst
tst/standard/grahom.tst

This PR implements the Welsh-Powell algorithm for digraph colouring. This implementation is almost always as good as the previous one (in terms of the number of colours required), and is faster (approx.
4 times faster on `DigraphRemoveLoops(RandomDigraph(10000, 0.1)))`.

Improve DigraphColouring

---

doc/oper.xml
doc/z-chap4.xml
gap/oper.gd
gap/oper.gi
tst/standard/oper.tst

This pull request implements a `DigraphShortestPath` method, which takes a digraphs and two positive integers, and returns a list in the same format as `DigraphPath`.
The shortest path is found using a breadth-first search.

Add DigraphShortestPath method

---

gap/digraph.gd
gap/digraph.gi
tst/standard/digraph.tst

This small PR allows the use of rationals in addition to floats for the second argument of `RandomDigraph`.

Allow rational numbers as the second argument of RandomDigraph

---

doc/display.xml
doc/z-chap9.xml
gap/display.gd
gap/display.gi
tst/standard/display.tst

This PR adds a method for producing a dot string where a subdigraph is highlighted.
I'm open to comments if people would like this to work differently - I wrote it this way for a specific application, and it might not be the best generic solution.

add DotHighlightedDigraph method

---

doc/attr.xml
doc/z-chap4.xml
gap/attr.gd
gap/attr.gi
tst/standard/attr.tst

This pull requests adds an attribute DigraphNrStronglyConnectedComponents, which takes a digraph as its argument and returns the number of strongly connected components of the digraph.
The feature was suggested in [this issue](https://github.com/gap-packages/Digraphs/issues/176).

Added DigraphNrStronglyConnectedComponents attribute

---

doc/oper.xml
doc/z-chap4.xml
gap/oper.gd
gap/oper.gi
tst/standard/oper.tst

This PR adds a method for constructing Clifford semigroups as partial permutation semigroups, given a semilattice, groups, and homomorphisms.
You can choose between an easily-computed representation (the default) and a more difficult but possibly smaller degree representation. The smaller degree representation is based on 
"The minimal faithful degree of a semilattice of groups"
David Easdown
J. Austral. Math. Soc. (Series A) 45 (1988), 341-350

Add AsSemigroup method for strong semilattices of groups

---

gap/prop.gi

Use BooleanAdjacencyMatrixMutableCopy in IsHamiltonianDigraph

---

doc/attr.xml
doc/z-chap2.xml
gap/attr.gd
gap/attr.gi
tst/standard/attr.tst

This pull request adds a function which takes a symmetric digraph, and returns its Mycielskian.
The Mycielskian of a symmetric digraph is a larger symmetric digraph constructed from it, which has greater chromatic number. For more information on the construction, see [here](https://en.wikipedia.org/wiki/Mycielskian).

Added DigraphMycielskian function

---

src/homos.c

The latter is kinda deprecated (I'll add a comment to the GAP header `stringobj.h` making that explicit.
This PR could also use `MakeImmString` instead of `MakeString`, to produce an immutable string; but I played it safe, and made sure to not change the semantics of the code.

Use MakeString instead of C_NEW_STRING

---

doc/grahom.xml
gap/attr.gi
tst/standard/grahom.tst
tst/standard/prop.tst

This code was recently refactored; the problem is that the assignment of colours to vertices didn't give a colour to isolated vertices. This bug was only ever present in `master`, it wasn't released.
Resolves #199.

Fix DIGRAPHS_Bipartite for digraphs with isolated vertices

---

doc/digraph.xml
doc/exmpl.xml

This pull request fixes a typo in the JohnsonDigraph documentation, to refer to the k subsets of the range [1 .. n], rather than [1 .. k]. It also moves the JohnsonDigraph documentation to the `exmpl.xml` file, to be more consistent with the fact that JohnsonDigraph is written in the file `exmpl.gi`.

Fix typo in JohnsonDigraph documentation and move to exmpl.xml file

---

Makefile.am
configure.ac
m4/ax_append_compile_flags.m4
m4/ax_append_flag.m4
m4/ax_check_compile_flag.m4
m4/ax_code_coverage.m4
m4/ax_compiler_flags_cflags.m4
m4/ax_compiler_flags_cxxflags.m4
m4/ax_require_defined.m4

This PR removes a hack in the build system and properly installs warning flags and the configure option `--enable-compile-warnings`.

build: properly install warning flags

---

doc/oper.xml
gap/labels.gi
gap/oper.gi
tst/standard/oper.tst

This pull request improves the way `DigraphVertexLabels` behaves with `DigraphRemoveVertex`, for mutable digraphs.
**Previously**
~~~
gap> D := CycleDigraph(IsMutableDigraph, 5);
<mutable digraph with 5 vertices, 5 edges>
gap> DigraphRemoveVertex(D, 1);
<mutable digraph with 4 vertices, 3 edges>
gap> DigraphVertexLabels(D);
[ 1 .. 4 ]
~~~
**With these commits**
~~~
gap> D := CycleDigraph(IsMutableDigraph, 5);
<mutable digraph with 5 vertices, 5 edges>
gap> DigraphRemoveVertex(D, 1);
<mutable digraph with 4 vertices, 3 edges>
gap> DigraphVertexLabels(D);
[ 2, 3, 4, 5 ]
~~~

Improve DigraphVertexLabels and DigraphRemoveVertex for mutable digraphs

---

doc/prop.xml
doc/z-chap5.xml
gap/prop.gd
gap/prop.gi
tst/standard/prop.tst

This pull request adds a method for determining whether or not a digraph is a core. A digraph _D_ is a core if and only if every endomorphism on _D_ is an automorphism on _D_.

Add IsDigraphCore property

---

src/homos.c
tst/standard/grahom.tst

This PR fixes issue 222. Previously the monomorphism finding code did not properly ensure that the found homomorphisms were injective. This PR fixes this by removing all points in the image of a partial monomorphism from the set of vertices that can be chosen for the image of the next point.

Fix issue 222

---

doc/attr.xml
doc/z-chap4.xml
gap/attr.gd
gap/attr.gi
tst/standard/attr.tst

This PR adds the following attributes
- `DegreeMatrix` - for a digraph, returns the diagonal matrix whose `i`th diagonal entry is the outdegree of vertex `i`.
- `LaplacianMatrix` - for a digraph, returns the difference of the `DegreeMatrix` and `AdjacencyMatrix` of the digraph.
- `NrSpanningTrees` - for a symmetric digraph, returns the number of spanning trees of that digraph. Calculated by computing the determinant of `LaplacianMatrix` with a single row and column removed. Time complexity `O(n^3)`.
See Issue #197.

Add NrSpanningTrees attribute

---

doc/attr.xml
doc/z-chap6.xml
gap/attr.gd
gap/attr.gi
tst/standard/attr.tst

This pull request adds a method `DigraphCore`, which takes a digraph and returns its core.
The core of a digraph _D_ is the (unique up to isomorphism) minimal subdigraph which is a homomorphic image of _D_.
The method works by searching for endomorphisms of the argument digraph, alternating between looking for ones of the smallest and largest possible rank. If one of the smallest possible rank is found, then the procedure stops. If one of the largest possible rank is found, then unnecessary parts of the digraph are removed from consideration.
In the case where the digraph is non-connected, the method computes the core of each connected component and then combines them in the minimal possible way, rather than searching for the core of the digraph as a whole. This works significantly faster …

Add DigraphCore method

---

gap/attr.gi
gap/cliques.gi
gap/cnstr.gi
gap/digraph.gd
gap/digraph.gi
gap/display.gi
gap/exmpl.gi
gap/grahom.gi
gap/grape.gi
gap/io.gi
gap/isomorph.gi
gap/labels.gi
gap/oper.gi
gap/orbits.gi
gap/planar.gi
gap/prop.gi
tst/standard/attr.tst
tst/standard/digraph.tst
tst/standard/oper.tst
tst/testinstall.tst

Using the function `PostMakeImmutable` to do the important stuff previously done in `MakeImmutableDigraph`.

Make digraphs immutable via MakeImmutable

---

gap/cliques.gi
tst/standard/cliques.tst

The problem with #240 was that some cliques were created using the function `Orb`, which gives immutable objects, but otherwise the cliques tended to be mutable.
Now everything is always immutable.
Fixes #240.

Make gap/cliques.gi always return immutable lists (of lists)

---

gap/oper.gi
tst/standard/oper.tst

This pull request fixes the unexpected behaviour of `DigraphDisjointUnion`, detailed in issue #227.
Fixes #227.

Resolve issue #227

---

doc/labels.xml
gap/display.gi

While working on display.xml I came across a bug in `DotPartialOrderDigraph` - it modifies mutable digraphs in place instead of making a copy. This PR fixes it.

Fix error in DotPartialOrderDigraph

---

doc/grape.xml

This pull requests updates the documentation in `grape.xml`. The functions can't return mutable digraphs, and nor can they accept them as arguments: the documentation now reflects this.

Update grape.xml documentation

---

gap/attr.gd
gap/attr.gi
gap/digraphs.g
gap/isomorph.gd
gap/isomorph.gi

This fixes the changes in #247, and provides a couple of extra examples of the usage of `DeclareMethodThatReturnsDigraph` and `InstallMethodThatReturnsDigraph`.

Add InstallMethodThatReturnsDigraph

---

doc/attr.xml
doc/oper.xml
doc/z-chap2.xml
gap/attr.gd
gap/oper.gd
gap/oper.gi
tst/standard/attr.tst
tst/standard/oper.tst

This PR implements two types of digraph product as discussed in #226 for a collection of digraphs. `DigraphCartesianProduct` computes the [Cartesian product](https://en.wikipedia.org/wiki/Cartesian_product_of_graphs) of a collection of digraphs and `DigraphDirectProduct` computes the [direct product](https://en.wikipedia.org/wiki/Tensor_product_of_graphs) of a collection of digraphs. It also includes two new attributes `DigraphCartesianProductProjections` and `DigraphDirectProductProjections` for storing projections onto the coordinates of vertices.
Since the vertex set of `DigraphCartesianProduct(G, H)` is the Cartesian product of the vertex sets of `G` and `H`, but the `Digraphs` package does not permit a vertex set to contain pairs of integers, only integers themselves, then we encode …

Add DigraphCartesianProduct and DigraphDirectProduct methods

---

doc/io.xml
gap/io.gd
gap/io.gi
tst/standard/io.tst

This pull request adds the functionality for `DigraphFromDigraph6String` to return mutable digraphs.

DigraphFromDigraph6String ability to return mutable digraphs

---

src/digraphs.c

This closes #266. This means that Digraphs should compile cleanly on GAP 4.9 (even though it already still works, because this code cannot be executed).
This whitespace changes were made automatically by cpplint (I think) or whatever hook I have installed. So they're not my fault.

Remove redundant C code in FuncOutNeighbours

---

gap/digraph.gi
tst/testinstall.tst

The problem was that there was `IsDigraph(D)` written rather than `IsCompleteDigraph(D)`.
Closes #272.

Fix ViewString for known non-complete digraphs

---

src/bitarray.h

This fixes a compiler warning  given by gcc.

bitarray: fix compile warning

---

src/digraphs.c

I'm writing some code that involves a very large number of calls to the homomorphism finding code for relatively small digraphs. One things that stood out when profiling that code was that `DigraphNrVertices` uses more time than maybe necessary. This PR optimises the C code for `DigraphNrVertices`.
In the `stable-1.0` branch:
~~~~
gap> D := CompleteDigraph(2);;
gap> for i in [1 .. 100000] do
> HomomorphismDigraphsFinder(D, D, fail, [], 1, 2, 0, [1, 2],
> [], [[1, 2]], [[1, 2]]);
> od;
gap> time;
1205
~~~~
with this PR:
~~~~
gap> D := CompleteDigraph(2);;
gap> for i in [1 .. 100000] do
> HomomorphismDigraphsFinder(D, D, fail, [], 1, 2, 0, [1, 2],
> [], [[1, 2]], [[1, 2]]);
> od;
gap> time;
1073
~~~~
a modest saving, but a saving nonetheless.

kernel: optimize OutNeighbours

---

doc/grahom.xml
doc/isomorph.xml
gap/grahom.gd
gap/grahom.gi
gap/isomorph.gd
gap/isomorph.gi
src/digraphs.c
src/homos-graphs.c
src/homos-graphs.h
src/homos.c
src/perms.c
src/perms.h
tst/standard/grahom.tst
tst/standard/isomorph.tst

This PR allows the user to specify a subgroup of the automorphism group to `HomomorphismDigraphsFinder`. Representatives of homomorphisms are then returned up to right multiplication by elements of the automorphism subgroup.
This PR also fixes a bug where non-embeddings could be returned when the embedding option was chosen.
This PR deals with #279 and is based on #283

Allow user to specify automorphisms in HomomorphismDigraphsFinder

---

.gitignore
PackageInfo.g
extern/bliss-0.73/.clang-format
extern/bliss-0.73/bignum.hh
extern/bliss-0.73/bliss.cc
extern/bliss-0.73/bliss_C.cc
extern/bliss-0.73/bliss_C.h
extern/bliss-0.73/defs.cc
extern/bliss-0.73/defs.hh
extern/bliss-0.73/graph.cc
extern/bliss-0.73/graph.hh
extern/bliss-0.73/heap.cc
extern/bliss-0.73/heap.hh
extern/bliss-0.73/kqueue.hh
extern/bliss-0.73/kstack.hh
extern/bliss-0.73/orbit.cc
extern/bliss-0.73/orbit.hh
extern/bliss-0.73/partition.cc
extern/bliss-0.73/partition.hh
extern/bliss-0.73/timer.cc
extern/bliss-0.73/timer.hh
extern/bliss-0.73/uintseqhash.cc
extern/bliss-0.73/uintseqhash.hh
extern/bliss-0.73/utils.cc
extern/bliss-0.73/utils.hh
src/bitarray.h
src/digraphs.c
src/homos-graphs.c
src/homos-graphs.h
src/homos.c

The purpose of this PR is to remove the use of `malloc` in the version of bliss that's vendored  by Digraphs. The rationale behind this is the same as in PR #281:
> I'm writing some code that involves a very large number of calls to the homomorphism finding code for relatively small digraphs. 
Another thing that stands out when profiling this is that the top three or four things in the profile are all related to bliss mallocing and freeing memory. This PR will make it possible for the homomorphism finding code in GAP to modify a bliss graph in-place (without any memory allocation or deallocation), and repeatedly reuse that graph and all of its associated data structures in `bliss` for finding the automorphism group. 
With this PR (in its current unfinished state):
~~~~
gap> D := …

No malloc bliss

---

src/homos-graphs.c

It seems that Digraphs doesn't check compilation in debug mode in the travis test :(

Fix assertion

---

src/homos-graphs.c

This fixes the Semigroups tests that are currently failing at:
https://travis-ci.org/gap-packages/Semigroups/jobs/643282462#L4068
And might be related to:
https://github.com/gap-packages/Semigroups/issues/634
Although the above Semigroups issue might also not be related, because it appears that the bug that this PR fixes was added recently in PR #282.

Fix bug in digraph homom. finder

---

doc/io.xml
doc/z-chap9.xml
gap/digraph.gi
tst/standard/digraph.tst
tst/standard/display.tst

This pull request improves the `String` method for Digraphs, as suggested in #233. With these changes, for a digraph `D`, `String(D)` returns a string `str` of minimal length such that when the output of `Print(str)` is run, `D` is returned. This is advantageous in that a user need no longer compare the length of the `OutNeighbours` representation, the `Digraph6String` representation, the `DiSparse6String` representation, etc. For example,
~~~
gap> D := CycleDigraph(IsMutableDigraph, 20);
<mutable digraph with 20 vertices, 20 edges>
gap> String(D);
"DigraphFromDiSparse6String(IsMutableDigraph, \".Sr?s_`abcdefghijklmnopq\");"
gap> Print(last);
DigraphFromDiSparse6String(IsMutableDigraph, ".Sr?s_`abcdefghijklmnopq");
gap> DigraphFromDiSparse6String(IsMutableDigraph, …

Improve String method for a digraph, to give shorter strings

---

.travis.yml
Makefile.am
configure.ac

This should resolve Issue #293, @isuruf I added a single flag that disables `-mpopcnt`, `-march=native` and `__builtin_ctzll`. You didn't ask for the last one but I guess it's desirable to disable it too?

Without intrinsics

---

doc/attr.xml
doc/oper.xml
doc/z-chap4.xml
gap/attr.gd
gap/attr.gi
gap/oper.gd
gap/oper.gi
tst/standard/attr.tst
tst/standard/oper.tst

This PR adds the following attributes and property:  
* `DigraphMaximalMatching` - for a digraph, this attribute returns a maximal matching of the digraph.
* `DigraphMaximumMatching` - for a digraph, this attribute returns a maximum matching of the digraph.
* `IsMaximumMatching` - for a digraph, and list of pairs of vertices, returns true if the list is a valid maximum matching of the digraph and false otherwise.  
See issue #155.  
A matching of a graph is a subset of the edges such that no pair of edges are incident at a vertex. A matching is *maximal* if it cannot be extended by adding an edge. A matching is *maximum* if it has maximum cardinality among all possible matchings. Note that the Digraphs package definition of matching allows the inclusion of loops in a matching.  
If what …

Add DigraphMaximumMatching

---

scripts/travis-build-dependencies.sh

Use a temporary version of NautyTracesInterface because the upstream is currently broken. 
See: 
https://github.com/gap-packages/NautyTracesInterface/pull/34
https://github.com/gap-packages/Digraphs/pull/308
https://github.com/gap-packages/NautyTracesInterface/issues/33

travis: fix NautyTracesInterface

---

CHANGELOG.md

I always think it's nice to mention such things.

CHANGELOG: mention that datastructures is now required

---

.travis.yml

In commit https://github.com/gap-packages/Digraphs/commit/8fba7f376f235c3b9f199aaeae4623bb277690cf, the `.travis.yml` file was changed so that Travis would build only [PRs, and] commits pushed to the `master` and `stable` branches of Digraphs. I would like the effect of this change to be reversed.
@james-d-mitchell Was the purpose of commit https://github.com/gap-packages/Digraphs/commit/8fba7f376f235c3b9f199aaeae4623bb277690cf was to stop the `rc-v1.2.0` (etc) branches from being built, thereby reducing the release process time? If so, the same effect can be achieved with this PR. If there are deeper reasons, let's discuss...
_(Explanation of my motivations:)_
I work on this package (and other packages) by creating named branches on my computer, and then pushing them to my own fork. I …

Travis: build all branches except release candidates

---

.travis.yml
scripts/travis-test.sh

See #316. The job takes unreasonably long as-is. I think it's reasonable to just run the standard tests, since the main purpose of that job is to make sure that Digraphs actually runs with all of those options.
Fixes #316.

Travis: skip extreme tests for job with external bliss/planarity and without intrinsics

---

configure.ac
m4/find_gap.m4
scripts/travis-build-dependencies.sh
src/bitarray.c
src/bitarray.h
src/digraphs.h
src/homos-graphs.c
src/homos.c
src/homos.h
src/perms.h
src/planar.h

This will allow future GAP versions to simplify their GAP_CPPFLAGS,
which currently need to contain `-I$(abs_srcdir)` just to support this
old use case. Also, this in turn makes it easier to have package
compatible with future installed version of GAP, which have headers in
PREFIX/include/gap/ so there is no `src` there (unless downstream
packagers jump through hoops to ensure that, e.g. by adding a special
symlink).
Note: we could also #include "gap_all.h" but that would require GAP >= 4.11.

Change #include "src/compiled.h" to just "compiled.h"

---

src/homos.c
src/planar.c

Motivation: RetypeBag is a very low-level part of the GAP kernel, and kernel
extensions should ideally restrict use of it to what's really required. In
many cases, it is far better to avoid it, and instead use higher-level APIs
such as ASS_LIST to edit lists, instead of relying on the unsafe low-level API
SET_ELM_PLIST combined with RetypeBag.
However, in the two cases at hand, calling RetypeBag simply is unnecessary: In
the first one, the code actually uses ASS_LIST and as such any retyping is
automatically performed by the GAP kernel for us.
In the second case, an empty plist is marked as such explicitly by retyping it
to T_PLIST_EMPTY. But that's a purely optional optimization.

Remove two calls to RetypeBag from kernel extension

---

gap/digraph.gd
gap/digraph.gi
gap/labels.gd
gap/labels.gi
tst/standard/digraph.tst
tst/standard/labels.tst

We added a filter called `IsNotDefaultEdgeLabelled` that changes to true when we set edge labels and changes back into false when we clear them, so now when we copy digraphs edges are only copied if they are not the default ones, which improves efficiency.
This addresses issue #292.

Improve performance of CopyDigraph

---

PackageInfo.g

My location details were out of date. I prefer to leave them out now, rather than update them. I also prefer to be credited with my middle initial.

Update Wilf's details in PackageInfo.g

---

gap/digraph.gi
tst/standard/digraph.tst

Since symmetric digraphs are connected if and only if they are strongly connected, saying 'strongly' is unnecessary. We may as well not be unnecessarily verbose if we can help it.

Don't say "strongly connected" in the ViewString of symmetric digraphs

---

CHANGELOG.md
scripts/travis-build-dependencies.sh

Although the old link redirects to the current one, I think it makes sense to actually use the current one.

Update the URL for the main NautyTracesInterface repository

---

.github/workflows/GAP.yml
tst/testall.g

For now, this should suffice for getting a useful CI system back. This takes advantage of @ssiccha's work on https://github.com/gap-actions and @fingolfin's https://github.com/gap-system/pkg-ci-scripts. As you can see, it doesn't use much code.
Currently, all of the package tests are run with GAP `master` and `stable-4.11`. We can add `stable-4.10` and `stable-4.9` support if we manually compile NautyTracesInterface (which should be easy but that can come later).
This means we're missing the linting test, testing with different versions of packages, and also our custom code coverage test, for now. However, this system includeas Codecov integration - so we could look into turning that on. This also doesn't use Docker, but it is quite possible that someone using this kind of setup for a GAP …

Implement initial GitHub actions support for CI

---

gap/prop.gi
tst/standard/prop.tst

For the general method: first check whether there are an odd number of edges (ignoring loops), and return `false` if so. Computing `IsMultiDigraph`, `DigraphNrEdges`, and `DigraphLoops` should be a lot faster than computing the in-neighbours, which is what happens next.
And a method for when we have the adjacency matrix.

Small improvements to IsSymmetricDigraph

---

doc/oper.xml
gap/oper.gi
tst/standard/oper.tst

This is similar to #338 and #340, for edges (although I made these changes over a year ago!).

Don't copy an immutable digraph when adding zero vertices

---

doc/display.xml

This wrong name being used was causing a warning when compiling the documentation.
While fixing this, I also spotted a couple of typos.

Fix doc for DotSymmetric*ColoredDigraph

---

README.md

This adds a badge to the README showing the code coverage percentage and the build status in GitHub actions, both for the master branch.
Since we merge our stable branches into our master branch periodically, I don't see how we can easily have the badge showing the status for the master branch in the master branch, but showing the status for the stable branch in the stable branch. So I've just gone for the master branch everywhere.
You can see the result of this by scrolling down to [the README on this page](https://github.com/wilfwilson/Digraphs/tree/add-more-badges-to-README).
The GitHub actions badge will show 'no status' until we merge stable-1.3 into master. This is because the master branch doesn't yet have the fully up-to-date CI.

Add code coverage and GitHub actions badges to the README

---

doc/io.xml
gap/io.gi
tst/standard/io.tst

This resolves issue #374, there was one place where we failed to close a file in `io.gi` the other unclosed files arose from carelessness in the tests.

io: always close files (resolves Issue #374)

---

doc/attr.xml
doc/oper.xml

We should consistently refer to sections as `Section <nr>` rather than `section <nr>`.

Correct some capitalisation in the manual

---

doc/oper.xml
doc/z-chap2.xml
gap/attr.gi
gap/oper.gd
gap/oper.gi
tst/standard/oper.tst

Dear James and Wilf, 
I have been using digraphs in a course on group theory. When using CayleyDigraph, I noticed that there was a minor mistake during the creation of a CayleyDigraph. The action was OnRight, it should be OnLeftInverse
Furthermore, when playing with Rubik's cube, in particular the small one, it turned out that having an operation that returns a Shortest Path Spanning Tree with relation to a given vertex would be very handy. I noticed that such a tree is almost there when the ConnectivityDataForVertex is computed. I added some lines of code to make sure the tree is stored. Also it would be useful if the Edges of a CayleyDigraph were labeled, which I also did. 
Finally I've created an operation DigraphShortestPathSpanningTree
Best regards,
Jan

Add DigraphShortestPathSpanningTree

---

.github/workflows/ci.yml

This was slightly tricky to set up because:
* the newest `master` branch of `NautyTracesInterface` requires `GAP >=4.11`, so we don't install `NautyTracesInterface` for the `stable-4.10` job (which makes the `stable-4.10` job much faster than `stable-4.11` etc).
* the version of `datastructures` that is included with `GAP 4.10` is `0.2.4` which is too old for Digraphs. So we have to install a newer version separately.

Test against GAP stable-4.10 on GitHub Actions

---

init.g

This should remove one of the two remaining incompatibilities between Digraphs and YAGS; see https://github.com/yags/yags/issues/1#issuecomment-780504933.

init: only define GRAPE variables when undefined

---

tst/standard/attr.tst
tst/standard/cliques.tst
tst/standard/digraph.tst
tst/standard/display.tst
tst/standard/grahom.tst
tst/standard/io.tst
tst/standard/oper.tst
tst/standard/prop.tst

I have been slightly annoyed on occasion by long lines when looking in test files, so I just shortened them all to get it over and done with. It would be nice if the linter enforced line lengths on test files so they don't creep back in.
~~In the process of doing this, I discovered some commented-out tests in `tst/standard/display.tst` that I guess predate the Semigroups package requiring Digraphs, and Semigroups had its own copy of `Splash`?.~~
~~Everything seems fine with Semigroups loaded on my end. So reinstating these might improve our code coverage!~~

Shorten lines in standard test files

---

.codecov.yml
gap/attr.gi
tst/standard/attr.tst
tst/standard/digraph.tst

The individual changes are described in the commit messages.
* codecov: ignore root `*.g` files, `tst/testall.g`, and `gap/utils.gi`.
* `attr.gi`: remove duplicate `IsVertexTransitive` and `IsEdgeTransitive` methods.
* `attr.gi`: fix `if` statement in `DigraphOddGirth`.
* 100% code coverage in `attr.gi`.

100% code coverage for gap/attr.gi and associated small fixes and tweaks

---

doc/grahom.xml
doc/z-chap6.xml
gap/grahom.gd
gap/grahom.gi
tst/standard/grahom.tst

Implements the functions MaximalCommonSubdigraph and MinimalCommonSuperdigraph.
MaximalCommonSubdigraph takes 2 digraphs and returns a third digraph with maximum vertex set size which embedds in both of them (as well as the embeddings).
MinimalCommonSuperdigraph takes 2 digraphs and returns a third digraph with minimum vertex set size into which both of them embed (as well as the embeddings).
It also includes a function which builds the ModularProduct of 2 digraphs. This is analogous to the modular product of graphs as described here: https://en.wikipedia.org/wiki/Modular_product_of_graphs

Maximal common subdigraph/Minimal common superdigraph

---

doc/grape.xml
gap/grape.gi
tst/standard/grape.tst

~~I am working to get @jdebeule's PR #363 merged. As a start, I have taken out the bit about Cayley graphs and put it here (and added documentation and tests).~~
PR #363 is now merged. In finishing that PR, I extracted the bit about labels of Cayley digraphs, added documentation and tests, and made this PR.

Add vertex & edge labels to Cayley digraphs

---

gap/attr.gd
gap/attr.gi
src/digraphs.c

This PR makes `OutNeighbours` a function rather than an attribute, to avoid the performance penalty of the return value being copied for mutable digraphs. This might not be desirable, but I can't think why it isn't at the moment, and the fact that the test all run after this change at least partially indicates that it might be desirable. 
This resolves both #413 and #318.

Resolve Issue #413 (OutNeighbours performance)

---

.github/workflows/gap.yml
.github/workflows/lint.yml
Makefile.am
etc/cpplint.sh
etc/gaplint.sh

This does two things:
1. It implements the linting job along the lines of what Semigroups now does (although, see `.github/workflows/lint.yml`, it perhaps does it a slightly nicer way, combining the two jobs with one matrix).
2. It adds a new `if:` command to the workflows to skip some duplicate jobs on PRs. This means that when a PR is made from a branch in the same repository (e.g. this happens with our `rc-v1.4.1` branches), then the jobs are not run twice (as both a pushed branch, and as a PR). In particular, this skips the jobs associated with the PR, and keeps the jobs for the push. Previously we handled this case with an exception for `rc-v[0-9]+.[0-9]+.[0-9]+` branches, but this is a general solution for any name of branch.
The result is not completely pretty, but [it looks …

Update GitHub actions integration

---

doc/attr.xml
doc/cliques.xml
doc/digraph.xml

Fix some misspellings and other heinous errors in the manual.

doc: fix typo in the doc

---

doc/labels.xml
gap/labels.gi
tst/standard/labels.tst

This PR fixes issue #414, per the discussion with @james-d-mitchell and @wilfwilson.
When calling `SetDigraphVertexLabels` with an immutable list, the list is replaced with a mutable copy of itself, so that a digraph's vertex labels can't be immutable.

Copy immutable lists given to `SetDigraphVertexLabels` (Issue #414)

---

ci/docker-test.sh
scripts/travis-build-dependencies.sh

Previously we were scraping the webpage of package releases. No we're at least scraping the API page for the package releases, which is hopefully slightly less likely to change.
(Ultimately this could be done much more robustly by properly interacting with the GitHub API, but that would take time, and here's a quick fix, hopefully!)
It's also not good that some of the CI scripts are essentially duplicated between Appveyor and Azure Pipelines. Unifying them, or abandoning Appveyor (possibly in favour of Cwygin in GitHub Actions) would be a good idea imo.

Fix CI: get latest package versions slightly more robustly, via the GitHub API

---

doc/examples.xml
doc/z-chap2.xml
gap/examples.gd
gap/examples.gi
tst/standard/examples.tst

This adds a constructor function for the [Knight's Graph](https://en.wikipedia.org/wiki/Knight%27s_graph).

Knightsgraph

---

doc/examples.xml
doc/z-chap2.xml
gap/examples.gd
gap/examples.gi
gap/utils.gd
gap/utils.gi
tst/standard/examples.tst

Add global function for generating a [Haar Graph](https://mathworld.wolfram.com/HaarGraph.html) based on a single parameter. @flsmith

Add HaarGraph

---

doc/examples.xml
doc/z-chap2.xml
gap/examples.gd
gap/examples.gi
tst/standard/examples.tst

Added two new operations, for constructing square and triangular [grid graphs](https://en.wikipedia.org/wiki/Lattice_graph). Also added tests for these functions.

Add GridGraph

---

gap/display.gi

* This addresses a TODO; `StringFormatted` was only added in GAP 4.10, but we now require it, so we can use it.
* Some of the `else` blocks were unreachable and had syntax errors.
* I've made the code in some of the methods a bit clearer, I think.

display: simplify some `Dot...` methods, and use StringFormatted

---

doc/attr.xml
doc/examples.xml
doc/oper.xml
gap/attr.gi
gap/digraph.gi
gap/prop.gd
tst/standard/attr.tst
tst/standard/examples.tst

I realised that undirected trees and forests didn't know that they were bipartite, so I've added this implication via an `InstallTrueMethod`. `UndirectedSpanningTree`s also didn't know that they were undirected trees, so I've added this too.
It then became a bit weird that these digraphs would be shown as `<immutable bipartite symmetric connected  digraph...>` or something like that.
The `ViewString`s now say "...forest digraph..." and "...tree digraph..." - should I drop the 'digraph'? I thought it best to keep it in, so that it's clear to a user that these are digraph objects, but I'm not strongly of that opinion.

ViewString: special case for trees and forests

---

gap/attr.gi
tst/standard/attr.tst

See #436.
The generic part of the method for `DigraphCore` assumes a lower bound of there being three vertices in the core.
The core can't contain only one vertex, since this can only happen when the digraph is either empty, or has a loop - but by the time the generic part of the method is encountered, these cases have been excluded. However, I don't see a good reason to rule out the core having only two vertices.
In any case, changing the default lower bound from should not affect mathematical correctness of results - the only problem is that we're widening the search size for the core. But the test cases that I've added show that this is necessary, anyway (at least in general).

Fix DigraphCore

---

doc/examples.xml
gap/examples.gd
tst/standard/examples.tst

Add DigraphCycle as a synonym for CycleDigraph

---

gap/attr.gi
tst/standard/attr.tst

https://en.wikipedia.org/wiki/Brooks'_theorem:
> For any connected undirected graph G with maximum degree Δ, the chromatic number of G is at most Δ, unless G is a complete graph or an odd cycle, in which case the chromatic number is Δ + 1
The greedy colouring algorithm can sometimes give Δ + 1 as an upper bound  (and maybe more?) when Brooks' theorem gives us just Δ. So let's take the minimum of the two in `ChromaticNumber`.

Improve ChromaticNumber with Brooks' theorem

---

gap/digraph.gi
gap/examples.gi
gap/prop.gd
gap/prop.gi

* Some properties were set to be true in the `CycleDigraph` creation function that should rather be `TrueMethods` for all things satisfying `IsCycleDigraph`.
* Strongly connected tournaments are Hamiltonian.
* Stop the `ViewString` '`<(im)mutable cycle tournament with 3 vertices>`' from happening: I think `<(im)mutable cycle digraph with 3 vertices>` is already specific enough, I think.
* Test the number of edges in `IsCycleDigraph` before testing strong connectivity, as it should be the cheaper test.

Improve ViewStrings/TrueMethods for tournaments/cycle digraphs

---

.github/workflows/gap.yml
.github/workflows/lint.yml

The GAP and linting jobs will run every morning at 3:30 GMT / 4:30 BST. Once this is merged into `master`, it will then be possible to go to https://github.com/digraphs/Digraphs/actions/workflows/gap.yml and https://github.com/digraphs/Digraphs/actions/workflows/lint.yml and choose to manually start a run of the corresponding tests on whichever branch you choose.

Run GitHub Actions tests on a daily schedule, and allow jobs to be started manually too

---

gap/attr.gi
tst/standard/attr.tst

This fixes a bug reported by @lhsoicher in #461.
There, he creates a digraph whose vertex labels are lists. However, `DigraphMaximumMatching` gives an error when run on this digraph, because the method makes invalid assumptions about the vertex labels.
Since the method for `DigraphMaximumMatching` works with a copy (this could perhaps be avoided to give a performance boost, but that's a separate issue...), then this can be easily fixed by setting the copy `D` to have vertex labels `DigraphVertices(D)`, i.e. `[1..n]` for `n := DigraphNrVertices(D)`.

Fix `DigraphMaximumMatching` for digraphs with custom vertex labels

---

gap/oper.gi
tst/standard/oper.tst

By 'combination operations', I mean `DigraphEdgeUnion`, `DigraphJoin`, `DigraphDisjointUnion`, `DigraphDirectProduct`, and `DigraphCartesianProduct`. See #467.
Given a list of digraphs, these operations would try to change this list. Therefore, they would either wrongly mutate this list, if it was mutable, else they would give an error when this failed.
Note: this concerns mutability of lists, not digraphs.
To fix this, I made `DIGRAPHS_CombinationOperProcessArgs` copy its argument, and return that copy when it is finished.
Resolves issue #467.

Stop the 'combination operations' from changing their given list of digraphs

---

gap/grape.gi
tst/standard/grape.tst

There was a subtle mistake in the constructor of `CayleyDigraph` at the point where the labels are set, one cannot just use the given list of generators. Few lines of code were added to correct the problem. This pull request is the adaptation of PR #451, but now I took care of some gaplint comments and found one more small mistake I made.

Fix the edge labels of Cayley digraphs

---

PackageInfo.g
ci/docker-test.sh
gap/doc.g
gap/utils.gi
makedoc.g
read.g
tst/testall.g

This is the analogous change to https://github.com/semigroups/Semigroups/pull/748, for the same reasons.
Also it will be useful because I want to add to separate CI job to compile and upload the manuals, and this will mean that that job won't have to compile anything except for GAP itself (and so will be nice and quick).
In fact, this solution ended up being a bit more robust than the new Semigroups implementation, and it raised some issues with the Semigroups implementation. So I'll try to make the corresponding changes there.

Enable the manual to be compiled without loading Digraphs

---

.github/workflows/gap.yml

The motivation of the refactoring is to:
* Make it easier to add the macOS job
* Make it easier to make my Windows job work (see #464)
* To separate the manual-building job from the `master` job, which was already the longest job. Therefore things should be quicker overall.

CI: refactor the CI a bit, and add a macOS job

---

doc/prop.xml

There is no 'the empty digraph' in this package; we have an empty digraph for each number of vertices.

Clarify the wording of an edge case in the documentation of `IsDirectedTree`

---

PackageInfo.g
tst/teststandard.g

The `TestFile` component of the `PackageInfo` record is used by the GAP testing setup to do automated tests of packages (Jenkins; plus publicly available setup that used to be on Travis, and will hopefully be soon replicated on GitHub Actions).
The test file that's pointed to is supposed to finish quite quickly. Currently we use `tst/testinstall.tst` for this, which is certainly quick, but is not very thorough. I think that the standard test suite (plus manual examples) is quick enough to be included, and much more comprehensive.
This doesn't affect anything about how our CI own setup works.

Add `tst/teststandard.g` and use it as the `PackageInfo.g` testfile

---

.release

So far, we only need to remove some additional files. I accidentally included some of these in the release of Digraphs v1.4.1.
This assumes that you're using the latest version of ReleaseTools.

Add a `.release` helper script for the release system

---

gap/examples.gi

Makes sense to re-use a tiny bit of our existing code, this also makes the connection to the explicitly-documented behaviour quite clear (i.e. vertex 1 being the 'centre' of the star).

Use `CompleteBipartiteDigraph` in `StarDigraph`

---

.github/workflows/gap.yml
tst/github_actions/examples.g
tst/github_actions/extreme.g
tst/github_actions/install.g
tst/github_actions/standard.g

A small change that will make it quicker to see which bit of the test suite has failed. See https://github.com/wilfwilson/Digraphs/runs/2646648699?check_suite_focus=true for an example where `TestStandard` and `TestExtreme` both fail, but `TestInstall` and `TestManualExamples` both pass.
All of the testing functions are run even if one of them fails, and code coverage is uploaded even if one of them fails.

Split the four test functions into different steps in GitHub Actions

---

doc/examples.xml
doc/z-chap2.xml
gap/examples.gd
gap/examples.gi
tst/standard/examples.tst

This fixes the issue raised in https://github.com/digraphs/Digraphs/issues/444
In this pull request:
- StarDigraph is changed to StarGraph
- TadpoleDigraph is changed to TadpoleGraph
- BookDigraph is changed to BookGraph

Renamed three functions for consistency

---

doc/attr.xml
doc/digraphs.bib
gap/attr.gi
init.g
tst/standard/attr.tst

This leaves the current attribute for chromatic number in place, but adds an alternative operation that takes an object which determines which algorithm to use. These algorithms are currently slower than the current implementation, but have space for later optimisation (being able to specify a bound for the maximum size of independent sets would be useful in this regard), but serve as a good baseline for later algorithms that will be added.
As part of the method selection, the files `algobj.gi` and `algobj.gd` were added. The purpose of these files is to contain objects that relate to method selection for algorithms, in this case it houses the objects used to select the colouring algorithm. Alongside this are a number of categories and filters, such as `IsDigraphAlgorithm` which serves as …

Add Lawler and Byskov's dynamic programming algorithms for chromatic number

---

.covignore
ci/docker-test.sh
gap/display.gi
tst/standard/display.tst

This PR makes it possible to un-comment some commented-out tests in `tst/standard/display.tst`, and to add some new ones for increased code coverage of `gap/display.gi`.
It's impossible or me to get 100% diff coverage, so that PR check will be failing, because I've changed the code that actually does the Splashing (which we can't/don't want to test in the test suites). I've checked that `Splash` still works for `dot` and `latex` files.
Therefore this PR will need to be merged with the failing `Codecov/patch` check.

Reinstate some `Splash` tests in `standard/display.tst`

---

configure.ac
extern/edge-addition-planarity-suite-Version_3.0.1.0/Makefile.am
extern/edge-addition-planarity-suite-Version_3.0.1.0/configure.ac

This PR removes some errors and comments puked out by newer versions of `autoconf`

build: update autotools

---

doc/examples.xml
doc/main.xml
doc/z-chap2.xml
gap/examples.gd
gap/examples.gi
gap/utils.gd
gap/utils.gi
tst/standard/examples.tst

examples: add binary tree

---

doc/digraph.xml
doc/examples.xml
doc/isomorph.xml
doc/main.xml
doc/prop.xml

Specifically:
* &STANDARD_FILT_TEXT;
* &MUTABLE_RECOMPUTED_PROP;
* &MUTABLE_RECOMPUTED_ATTR;
Also fixes some typos in `DigraphByInNeighbours` and adjusts some whitespace (😬).
These things are done in separate commits.
Resolves #478.

Use macros to reduce amounts of repeated text in the manual

---

doc/oper.xml
doc/z-chap2.xml
gap/oper.gd
gap/oper.gi
tst/standard/grahom.tst
tst/standard/oper.tst

This adds 4 additional graph product functions to the oper file. The graph products implemented are the [Strong Product](https://en.wikipedia.org/wiki/Strong_product_of_graphs), the [Co-normal Product](https://en.wikipedia.org/wiki/Graph_product), the [Homomorphic Product](https://en.wikipedia.org/wiki/Graph_product) and the [Lexicographic Product](https://en.wikipedia.org/wiki/Lexicographic_product_of_graphs). The function for the [Modular graph product](https://en.wikipedia.org/wiki/Modular_product_of_graphs) was also edited in order to reduce redundancies.

Implement several new graph products

---

doc/examples.xml
doc/z-chap2.xml
gap/examples.gd
gap/examples.gi
tst/standard/examples.tst

Implemented some new graph families and added 'wrappers' for some existing named graphs to preserve backwards compatibility.

Implemented several infinite families of named graphs

---

gap/oper.gi
tst/standard/oper.tst

This can significantly increase the performance of `DigraphAddEdge` for digraphs that do not have edge labels. See #500.

`DigraphAddEdge`: do not add an edge label if edge labels are not yet initialised

---

doc/prop.xml
doc/z-chap5.xml
gap/attr.gi
gap/digraph.gi
gap/grahom.gi
gap/isomorph.gi
gap/prop.gd
gap/prop.gi
tst/standard/prop.tst

I learned recently (see the discussion starting https://github.com/gap-system/gap/pull/4546#discussion_r646906841) that you can use
```
InstallTrueMethod( HasIsX, IsY );
```
to, in practice, automatically set `IsX(D) = false` when `IsY(D) = true` becomes known. The only pitfall is that if `IsX(D)` is already (i.e. wrongly) set to `true`, then this true method doesn't do anything; in particular it doesn't complain. So this doesn't help us to catch bugs (where properties get set incorrectly), but we weren't catching them anyway, and it does offer useful functionality for storing learned information.
Therefore I have added some such '`InstallFalseMethod`'s to Digraphs. This was made easier with the addition of `DigraphHasVertices` and `DigraphHasEdges`, which allows me to easily exclude some …

Add more implications (including some implications of falsity)

---

src/digraphs.c
tst/standard/digraph.tst

kernel: fix check in OutNeighbours

---

doc/oper.xml
doc/z-chap6.xml
gap/digraph.gd
gap/oper.gd
gap/oper.gi
tst/standard/oper.tst

I keep writing temporary functions to implement these actions for my research, so I thought it was about time I just add them to the package.
Tasks:

Add `OnTuplesDigraphs` and `OnSetsDigraphs`

---

.github/workflows/gap.yml

This should hopefully just work seamlessly. The `v1` version is [supposed to stop working at the end of the month](https://github.com/codecov/codecov-action#%EF%B8%8F--deprecration-of-v1).

CI: use codecov-action@v2 instead of @v1

---

doc/digraph.xml
gap/digraph.gd
gap/digraph.gi
tst/standard/digraph.tst

This PR adds an `AsDigraph` method for partial perms, and cleans up the documentation for `AsDigraph` as a bonus.

digraph: add AsDigraph for partial perms and fix doc

---

.github/workflows/stale.yml

Hopefully this means that the stale bot won't ever actually close any issues or PRs.

ci: never close issues/pr with stale bot

---

.gitattributes
.github/workflows/gap.yml

As discussed #464, the AppVeyor Windows tests broke and were therefore removed.
I think our philosophy with Windows tests should be to run them while it's convenient, but to spend as little effort as possible to maintain them.
The general-purpose CI setup for GAP packages that exists under the `gap-actions` organisation (which is what our GitHub Actions implementation already uses) current only works if you want to run tests on Ubuntu or macOS. I am working on making this work in Windows too, and I've got an initial version. I've not yet unified this with the existing Unix versions. Therefore I'm using my fork of several of the `gap-actions` repositories for now, which are specific to Windows.
Although this is not ideal, it's better than nothing, and if it stops working then we can scrap …

Add GitHub Actions Windows tests

---

init.g

When starting GAP with `-A`, then first loading digraphs and afterwards
loading grape, the following error was produced:
Error, variable `Vertices' is not bound to an operation at GAPROOT/lib/oper.g:940 called from
<function "DeclareOperation">( <arguments> )
called from read-eval loop at GAPROOT/pkg/grape-4.8.5/lib/grape.g:566
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue

Fix compatibility with grape

---

gap/grape.gi
init.g
read.g
tst/standard/digraph.tst
tst/standard/grape.tst
tst/testinstall.tst

When loading digraphs before grape, then some code kept printing a warning
saying "Grape is not loaded", even though grape was loaded. This patch fixes
that.
Sorry, I didn't notice this one before. 
Note that even with this patch, it will skip some test if one now tries to run the Digraphs test suite, That's because `DIGRAPHS_OmitFromTests` is initialized once and then not updated. This could be fixed, e.g. by removing `DIGRAPHS_OmitFromTests` and modifying the code which currently uses it to directly use `DIGRAPHS_IsGrapeLoaded()` -- the code would arguably be simpler, too. But I don't know if you have plans to use `DIGRAPHS_OmitFromTests` more or have other needs for it, so I didn't do that in this PR.

More fixes for loading grape after digraphs

---

doc/oper.xml
doc/z-chap4.xml
gap/oper.gd
gap/oper.gi
tst/standard/oper.tst

This adds a new operation that executes a random walk on a graph, starting at a vertex, and having the desired length.
I haven't done doc or tests yet, but does this look like the right sort of thing?
Output is the same as DigraphPath: a pair `[v,a]` where
- `v` is the ordered list of vertices in the path;
- `a` is the list of indices of edges followed from each vertex (helps distinguish edges in multidigraphs).
```gap
gap> D := Digraph([[1, 2], [3], [2, 4], [1], [2, 4]]);                
<immutable digraph with 5 vertices, 8 edges>
gap> DigraphRandomWalk(D, 1, 4);
[ [ 1, 2, 3, 2, 3 ], [ 2, 1, 1, 1 ] ]
```
If we reach a sink, we cut the path short, so the final length might be less than requested.

Add DigraphRandomWalk

---

Makefile.am

Copying digraph.so over an existing digraph.so confuses macOS' code
signing system, leading to segfaults when trying to load that
digraph.so. As a workaround, delete the old digraph.so before copying
the new one into place.

Add a workaround for macOS code signing issues.

---

doc/attr.xml
doc/grahom.xml
doc/prop.xml
doc/z-chap5.xml
doc/z-chap6.xml
gap/attr.gd
gap/attr.gi
gap/grahom.gd
gap/grahom.gi
gap/oper.gi
gap/prop.gd
gap/prop.gi
tst/standard/attr.tst
tst/standard/grahom.tst
tst/standard/oper.tst
tst/standard/prop.tst

This PR adds a method for finding an embedding from a lattice digraph into another lattice digraph.
A lattice embedding is an injective lattice homomorphism. In terms of partial order digraphs (of which lattice digraphs are a type) a lattice homomorphism is a digraph homomorphism, which respects the meets and joins of all pairs of vertices.
There were two competing methods for `LatticeDigraphEmbedding`. The one in this pull request is based on the digraph homomorphism finding algorithm, where the notion that "meets must maps to meets, and joins must map to joins" is enforced. The other method called `RepresentativesDigraphsEmbeddings`, iterating through vertices to search for a digraph embedding which respects the meets and joins. When I update this PR, I will include some timing graphs …

Add `LatticeDigraphEmbedding` method

---

doc/prop.xml
doc/z-chap5.xml
gap/prop.gd
gap/prop.gi
tst/standard/prop.tst

**Note: This PR is on top of #538, which is in turn on top of #533.**
This PR adds the property `IsDistributiveLatticeDigraph`, which determines whether or not a digraph is a distributive lattice digraph. A digraph `D` is a distributive lattice digraph if it is a lattice digraph, and the operations `PartialOrderDigraphMeetOfVertices` and `PartialOrderDigraphJoinOfVertices` distributive over each other.
A lattice is distributive if and only if it the 'diamond' (`M3`) and 'pentagon' (`N5`) lattices described [here](https://en.wikipedia.org/wiki/Distributive_lattice#Characteristic_properties) are not sublattices. The method uses this characterisation.
Given a lattice digraph `D`, every lattice embedding from `M3` or `N5` into `D` is necessarily a digraph embedding of their corresponding …

Add `IsDistributiveLatticeDigraph` property

---

gap/grape.gi

... instead of `AsList`, to produce a stable output that does not depend on the specific GAP version, random sources or anything else.
This should fix CI tests for latest GAP master, where the output of `AsList` for permutation groups changed: it used to match `AsSet` but doesn't anymore. See https://github.com/gap-system/gap/pull/5216 for details.

Change `CayleyDigraph` to use `AsSet`

---

src/conditions.h
src/perms.h

... so that future GAP versions can stop installing /usr/local/include/gap/src

Avoid src/ prefix for GAP headers

---

tst/standard/display.tst

Previously, the tests in display.tst try to call Splash with "xpdf" as the viewer, and we expect an error to be thrown.  This only works if xpdf is not installed, and if xpdf is installed then the tests fail.
This commit changes the test to a dummy viewer which will definitely not be installed.

Change test that relies on xpdf not being installed

---

gap/prop.gi
tst/standard/prop.tst

A few observations that can get us certain properties for free:
- `IsStronglyConnectedDigraph` implies `IsConnectedDigraph`;
- One `DigraphStronglyConnectedComponent` implies `IsStronglyConnectedDigraph`;
- One `DigraphConnectedComponent` implies `IsConnectedDigraph`.
This PR adds a couple of quick immediate methods that give us these.

Add immediate methods for connected and strongly connected graphs

---

gap/attr.gi

The currently-existing methods for `UndirectedSpanningForest` in `attr.gi` date from quite a while ago, during a time when we dealt with mutability in a mix of different ways.
(`UndirectedSpanningForest` is a bit special, since it delegates to a C method that takes and returns a list of adjacencies - I think that's why it's been untouched for a while.)
In this PR I've made `UndirectedSpanningForest` a bit more normal, I think. The setup now has a similar structure to `UndirectedSpanningTree`, which comes just after it in the file. In particular, this lets us remove the use of a `SUM_FLAGS` and of having to explicitly do `SetUndirectedSpanningForestAttr`.
There is now the slightest bit of code duplication, but in my opinion this is a price worth paying for the increased clarity of the …

Standardise the way that `UndirectedSpanningForest` works in relation to mutability

---

src/homos-graphs.c
src/homos.c

This PR arose from the discussion at:
https://github.com/semigroups/Semigroups/issues/948
https://github.com/semigroups/Semigroups/pull/942#issuecomment-1712458666

kernel: fix mem leaks for permutations allocated but not freed.

---

ci/coverage.py
ci/docker-test.sh
scripts/check-code-coverage.sh

Resolves #595
(It seems `master` and `stable-1.6` have diverged, neither is a subset of the other, so I am just guessing that this PR should go to stable-1.6?)

Remove references to bin/gap.sh

---

doc/weights.xml
doc/z-chap5.xml
gap/digraph.gi
gap/doc.g
gap/weights.gd
gap/weights.gi
init.g
read.g
tst/standard/digraph.tst
tst/standard/weights.tst
tst/testinstall.tst

This pull request effects:
- doc/z-chap5.xml: This adds the relevant Edge Weights heading with 2 labels: "EdgeWeights" and "EdgeWeightedDigraph"
- gap/doc.g: Adding weights.xml to the list of DIGRAPHS_DocXMLFiles
- init.g: Adding weights.gd to the packages to be read in
- Read.g: Adding weights.gi to the packages to be read in
- tst/testinstall.tst: Added a very basic test to test creation of EdgeWeightedDigraph
- doc/weights.xml: Added documentation
- gap/weights.gd: Added headers for functions implemented in weights.gi
- gap/weights.gi: Implemented EdgeWeightedDigraph
- tst/standard/weights.tst: Added tests for EdgeWeightedDigraph creation

Added EdgeWeightedDigraph

---

configure.ac

Using `==` for string equality only works in the Bash shell, while ./configure is meant to be run in any POSIX /bin/sh. We change one instance to `=` to fix the following error in (for example) Dash:
```
./configure: 5587: test: x: unexpected operator
```

configure.ac: fix bashism in string equality test

---

gap/digraph.gi
tst/standard/digraph.tst

as a preparation for https://github.com/gap-system/gap/pull/5418

Print empty lists with two spaces for consistency

---

gap/oper.gi
tst/testinstall.tst

Quick fix for #617.  Thanks to @saffronmciver for the report!
Fun fact: this fix involved removing 5 characters and adding 1 character.

Fix Issue #617: DigraphRemoveEdge now removes appropriate edge label

---

.github/workflows/gap.yml

This reverts commit b5f1306f6cdcf7d6b2a904d890192f5e1475e6be. Which hopefully (!?) will fix the cygwin ci job that seems to almost always time out now.

Revert "build(deps): bump codecov/codecov-action from 3 to 4"

---

doc/oper.xml
doc/z-chap2.xml
gap/oper.gd
gap/oper.gi
tst/standard/oper.tst
tst/testinstall.tst

Initial implementation of ContractEdge (see [Contract Edge Wikipedia Article](https://en.wikipedia.org/wiki/Edge_contraction); as discussed, this implementation should not create multiple edges). Mutable and Immutable methods exist for this. 
Edge labels should be handled if `DigraphRemoveEdge` were removing them, but this has not been tested yet because of this issue. 
Contract edge takes a non looping edge `(u, v)`, and contracts this into a single vertex `w`. The edge is removed, vertex labels are combined (in a list), and incident edges to `(u, v)` become incident to `w`. `MultiDigraphs` are not accepted into this function. If an edge `(v, u)` exists, this is also contracted (removed). 
Documentation has not been written yet (this is in progress).

Add DigraphContractEdge

---

configure.ac
extern/bliss-0.73/bliss_C.cc
extern/bliss-0.73/defs.cc
extern/bliss-0.73/graph.cc
extern/bliss-0.73/timer.cc
extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphDFSUtils.c
extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphDrawPlanar.c
extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphDrawPlanar_Extensions.c
extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphEmbed.c
extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphExtensions.c
extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphFunctionTable.h
extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphIO.c
extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphIsolator.c
extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphK23Search.c
extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphK23Search_Extensions.c
extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphK33Search.c
extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphK33Search_Extensions.c
extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphK4Search.c
extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphK4Search_Extensions.c
extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphOuterplanarObstruction.c
extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphTests.c
extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphUtils.c
extern/edge-addition-planarity-suite-Version_3.0.1.0/c/planarity.h
extern/edge-addition-planarity-suite-Version_3.0.1.0/c/planarityRandomGraphs.c
extern/edge-addition-planarity-suite-Version_3.0.1.0/c/planaritySpecificGraph.c
extern/edge-addition-planarity-suite-Version_3.0.1.0/c/planarityUtils.c
src/bliss-includes.h
src/digraphs.c
src/gap-includes.h
src/planar.c

This PR continues the work form #633 by fixing compiler warnings for GCC.

Fix compile warnings

---

src/digraphs.c

In digraphs.c we have a `FLOYD_WARSHALL` function that does a generalised version of the Floyd–Warshall algorithm with various options that customise the output.  As noted in comments, some of this was rather hacky, with flags for special cases that return a totally different type of object early in the function and so on.
This PR adds a `post` parameter to FLOYD_WARSHALL, which takes a post-processing function that inspects the state of the distance matrix and produces a final output.  So far we have three `post` functions:
- `FW_POST_DIAMETER`, used by `DIGRAPH_DIAMETER` (returns the highest number in the matrix, or fail)
- `FW_POST_HAS_CHANGED` used by `IS_TRANSITIVE_DIGRAPH` (returns a bool saying whether the matrix was changed in the main loop)
- `FW_POST_DISTANCES`, used by the …

Refactor Floyd–Warshall C implementation

---

PackageInfo.g
src/homos.c

This should fix the issue reported:
https://github.com/gap-system/PackageDistro/pull/987#issuecomment-2314495790
this caused a seg fault when running the semigroups package tests.

Fix off by one error

---

gap/attr.gi
gap/labels.gd
gap/labels.gi

Properly transfer the original vertices as labels of the vertices in the reduced graph in `DigraphAllSimpleCircuits`.

Resolve issue #676

---

.gitignore
PackageInfo.g

In release v1.8.0 we didn't increase the required version of GAP but we did start using `IsKernelExtensionAvailable` which was introduced in GAP 4.12. This lead to start up errors on versions of GAP earlier than 4.12, due to "unbound global variable" warnings.

Fix startup bug

---

doc/grahom.xml
doc/z-chap6.xml
gap/cliques.gi
gap/grahom.gd
gap/grahom.gi
gap/orbits.gd
gap/orbits.gi
gap/utils.gi
tst/standard/grahom.tst

Add `SubdigraphsMonomorphisms`

---

tst/standard/attr.tst

I've added a test for a version of the bug that @fingolfin reported in #676; see #678 which gave the fix.

Add a test for issue #676

---

doc/examples.xml
gap/examples.gi
tst/standard/examples.tst

Fix edge placement in HanoiGraph

---

.gitignore
doc/grahom.xml
doc/isomorph.xml
gap/grahom.gi
src/bitarray.c
src/bitarray.h
src/digraphs.c
src/digraphs.h
src/homos.c
src/perms.c
tst/extreme/grahom.tst
tst/standard/grahom.tst

This PR resolves #697, and some related issues discovered when trying to resolve it.
~~This PR adds some tests, and other minor fixes related to #697.~~
~~Before this can be merged I'll have to:~~

Clarify homomorphisms finder with specified image

---

.codecov.yml
read.g

Unfortunately this causes a warning when loading Digraphs in GAP 4.14.0

Remove references to non-existing gap/doc.g

---

src/digraphs.c

I hope targeting stable-1.9 is correct, if not let me know and I can change it.
This change is not crucial in any way but since I am currently looking into all packages with kernel extensions, and sending out some tweaks, I figured I might do this one, too :-)

Simplify kernel extension code setting up StructInitInfo

---

doc/weights.xml
tst/standard/weights.tst

A few tiny whitespace things I missed yesterday.

weights: tweak whitespace

---

gap/digraph.gi
src/digraphs.c
tst/standard/attr.tst

The previous implementation of RandomDigraph was heavily biased towards empty and complete digraphs. This PR improves that (though there is still a bit of a bias for these, for reasons I haven't looked into yet).
When not specified, the edge-probability is now chosen as `Float(Random(0, n^2) / n^2)`. Maybe it would be a good idea to take a slightly higher resolution to avoid any strange resolution effects, but I don't know what these effects might be. This probability done for all types of (non-multi) digraphs, even when `n^2` isn't the correct maximum number of edges, since it shouldn't have much effect.
I haven't changed RandomMultiDigraph as its behaviour is different - it takes as second parameter a desired number of edges instead of an edge-probability (I guess it isn't clear what …

Make random digraphs more random

---

PackageInfo.g

This is my second attempt at resolving [Issue 711](https://github.com/digraphs/Digraphs/issues/711).
Derived from XML, GAPDoc has macro substitution in the form of named entities. Calling a macro, e.g. &Digraphs;, will expand the html defined for the given named entity.
The intended behaviour of the calls is exhibited in Chapter 0 of the project manual [1].
More information about named entities can be found in Chapter 2.1-9 of the GAPDoc documentation manual [2].
AutoDoc doesn't seem to expand these macros. This results in the raw macro call being displayed in the places controlled by AutoDoc, namely the project homepage [3] and Digraphs' entry on the list of GAP packages [4].
Hence to prevent unnecessarily defining the Abstract twice, with different styling for GAPDoc and AutoDoc, …

Expand named entity GAPDoc calls in Abstract(HTML)

---

doc/grahom.xml
doc/z-chap0.xml

This PR removes the outdated list of contributors from the first chapter, and adds "subgraph isomorphism" to the index (addressing #561).

Minor doc updates

---

gap/isomorph.gi

This PR adds a more descriptive warnings for when `NautyAutomorphismGroup` is used with a `MultiDigraph`.

Add more descriptive warning when using `NautyAutomorphismGroup` with `MultiDigraph`s

---

doc/weights.xml
doc/z-chap5.xml
gap/weights.gd
gap/weights.gi
tst/standard/weights.tst

This was contributed by @RaiyanC, and is the next step in issue #746

Edge weights #5: maximum flow

---

gap/attr.gi

I have slightly refactored the UndirectedSpanningForest Function to calculate the Spanning Forest once instead of twice. This PR would resolve issue #581

Quick Refactor for UndirectedSpanningForest Function

---

gap/attr.gi
gap/grahom.gi
gap/isomorph.gi
gap/oper.gd
gap/oper.gi
tst/standard/oper.tst

This came up from some code which was heavily using digraphs. this almost doubled the speed of the algorithm, as it turns out these GAP-level checks were dominating the run-time of OnDigraphs.
* Instead of checking if the permutation fixes the vertices, check
if it is the identity (which is much cheaper, although catches
less cases)
* Do not check explictly if the permutation maps the vertices
of the graph to itself, do the mapping then check afterwards.

Speed up `OnDigraphs` for a digraph and a permutation

---

doc/attr.xml
doc/digraphs.bib
gap/attr.gi
tst/standard/attr.tst

Add Zykov and Christofides Algorithms for Chromatic Number. This builds on the previous pull request #382 to add two additional algorithms for calculating the Chromatic Number. These use the same method selection as the existing implementations, and so are simply additional options to use.

Add Zykov and Christofides Algorithms for Chromatic Number

---

gap/io.gi
tst/standard/io.tst

Related to #377, which ensured files close on error when decoding.
`ReadDigraphs` is leaving files open if a malformed file is fed in when using a whole file decoder (dreadnaut/dimacs) -- my bad. I had also carelessly left a file open in the tests. The suggested changes fixes those issues.
Something that's not my fault is that this issue propagates to encoding with `WriteDigraphs` but affects all file formats. I think this issue has probably been around for a while. If we encounter an error while encoding (i.e. due to the digraph being incompatible somehow with the file format), then the file isn't closed. For instance,
```
gap> filename := "/Users/pramothragavan/Downloads/10.txt";;
gap> D := Digraph([[2], []]);
<immutable digraph with 2 vertices, 1 edge>
gap> IO.OpenFiles;
[  ]
gap> …
```

Always close files (`ReadDigraphs`, `WriteDigraphs`)

---

src/gap-includes.h

Available since GAP 4.12, which this package requires anyway.

Use gap_all.h instead of compiled.h

---

doc/io.xml
doc/z-appB.xml
makedoc.g

I went all out and took the contents of the file that used to be available at http://mat.gsia.cmu.edu/COLOR/general/ccformat.ps, and put it into a new appendix in the Digraphs module.
Closes #734.

Replace broken DIMACS link by a new DIMACS appendix

---

doc/planar.xml

The documentation for `DualPlanarGraph` was a little non-standard, and also didn't explicitly state that it relies upon the edge-addition-planarity-suite. So I changed it.

Improve some planarity-related manual entries

---

.github/workflows/release.yml

I hadn't read the [`gap-actions/update-gh-pages` README](https://github.com/gap-actions/update-gh-pages/blob/main/README.md), so I didn't know about the existence of the `clean` option, which I think we want to be set to `false`.
I'll merge this as-is, but the real test will come when we make the next Digraphs release (which I'll do in the coming days, I hope).

Update the "Release" GitHub Action workflow to not wipe the website code with each new release

---

.github/workflows/release.yml

I'm hoping that this fixes #798.

Release CI: clone NautyTracesInterface so that we know its URL for `_data/package.yml`

---

.github/workflows/config_options.yml
.github/workflows/os.yml
.github/workflows/ubuntu.yml
.github/workflows/valgrind.yml

The latest GAP stable branch is GAP `stable-4.15`.  Where we test against all available supported GAP stable branches, I've added `stable-4.15` as an additional job. Where we were previously using just `stable-4.14` (i.e. as the "latest" stable branch, presumably), I've changed from `stable-4.14` to `stable-4.15`.
Also I'm attempting to incorporate a working version of #799.

CI: test against GAP `stable-4.15` as the latest stable branch

---

.github/workflows/release.yml
CHANGELOG.md

This uses some bash (involving some peculiar GitHub Actions syntax for getting multiline strings into an environment variable) with `grep` and `cut` and `sed` to extract the latest part of the `CHANGELOG.md` file, and pass it as input to the `release-pkg` action.
Also adds a "force" option to this workflow.

Use the `CHANGELOG` entry for the GitHub release in the GitHub Actions "Release" workflow

---

PackageInfo.g

For the HTML version of the abstract, just string-replace `&Digraphs;` and `&GAP;` by `<Strong>Digraphs</Strong>` and `<Strong>GAP</Strong>` respectively; that's how we want them anyway.
You can already see the result of this at https://digraphs.github.io/Digraphs.
Resolves #711.

PackageInfo.g: remove XML entities from `AbstractHTML`

---

.github/workflows/config_options.yml

This shouldn't have been added. I added it recently. It seems to have broken the `--enable-debug` jobs, so hopefully this will fix it.

CI: remove code coverage from config-options workflows

---

.github/workflows/os.yml
.github/workflows/ubuntu.yml

I like this for now. We can always go back to downloading a hardcoded specific tarball from one of the releases at the git repo <https://github.com/digraphs/digraphs-lib/releases>, or checking out a specific tag/branch.

Clone digraphs-lib rather than download a tarball

---

.github/workflows/ubuntu.yml
gap/attr.gi
makedoc.g
read.g
src/gap-includes.h
src/gap_all.h

Also remove the test against GAP v4.11 with only needed Digraphs packages. Since NautyTracesInterface doesn't run on GAP v4.11, the only difference between the default or only-needed jobs would be whether Grape is loaded - and I think that is tested sufficiently on the other jobs. So we can save those resources.

Restore compatibility with GAP 4.10 and test against it in the CI

---

gap/examples.gi
tst/testinstall.tst

This resolves the following bug:
```gap
gap> G:=CompleteBipartiteDigraph(1,5);
<immutable complete bipartite digraph with bicomponent sizes 1 and 5>
gap> DigraphBicomponents(G);
[ [ 1 ], [ 2, 3, 4, 5, 6 ] ]
gap> AutomorphismGroup(G);
Group([ (1,2,3,4,5), (1,2) ])
```
Simply put, our code was assuming that for `DirectProduct(SymmetricGroup([1]), SymmetricGroup([2..6]))`, GAP would return `SymmetricGroup([2..6])`. But in fact, GAP returns (the isomorphic, but not identical) `SymmetricGroup([1..5])`.
This bug is what was behind the wrong result reported by @bojankuzma000 in #850.

Fix `AutomorphismGroup` for `CompleteBipartiteDigraph(1,n)`
