doc/prop.xml
doc/z-chap5.xml
gap/prop.gd
gap/prop.gi
tst/standard/prop.tst

Adds a new function IsDirectedTree to test if a given digraph is a directed tree. (A directed tree is an acyclic digraph with precisely 1 source, such that no two vertices share an out-neighbour.)

Add IsDirectedTree

---

doc/prop.xml
doc/z-chap5.xml
gap/prop.gd
gap/prop.gi
tst/standard/prop.tst

created a property call IsUndirectedTree (an undirected tree is an undirected graph in which any 2 distinct vertices are connected by exactly 1 path.)

Add IsUndirectedTree

---

doc/attr.xml
doc/digraph.xml
doc/z-chap4.xml
gap/attr.gi
gap/digraph.gd
gap/digraph.gi
gap/oper.gi
gap/utils.gd
gap/utils.gi
tst/standard/attr.tst
tst/standard/digraph.tst

This is work in progress to add labels to edges.
My use case will be weighted graphs.

Add Operations to label edges in digraphs

---

doc/prop.xml
doc/z-chap5.xml
gap/prop.gd
gap/prop.gi
tst/standard/prop.tst

Adds property IsEulerianDigraph with it's documentation and testing

Is eulerian digraph

---

CHANGELOG.md
doc/io.xml
doc/z-chap9.xml
gap/io.gd
gap/io.gi
tst/standard/io.tst

The purpose of this PR is to address Issue #15 
I still need to add documentation and tests.

Add support for writing and reading DIMACS files

---

doc/oper.xml
doc/z-chap2.xml
gap/oper.gd
gap/oper.gi
tst/standard/oper.tst
tst/testinstall.tst

Adding an operation DigraphClosure which returns k-closure for a simple graph.

Added DigraphClosure

---

doc/prop.xml
doc/z-chap5.xml
gap/prop.gd
gap/prop.gi
tst/standard/prop.tst

And related documentation and tests.

prop: add IsCycleDigraph

---

doc/oper.xml
doc/z-chap4.xml
gap/oper.gd
gap/oper.gi
tst/standard/oper.tst

This PR replaces PR #66, which Isabella proposed. I reviewed that PR, and in this PR I made those changes and refactored the code.
This PR adds three new operations, `IsMatching`, `IsMaximalMatching`, and `IsPerfectMatching`, as well as a hidden function called `DIGRAPHS_IsMatching` which does all of the work. These functions are not complicated.

Add functions for testing matchings

---

Makefile.am
src/digraphs.c
src/homos.c

This PR fixes a critical bug in the kernel module relating to homomorphism finding, and cleans up  some other minor historical oddities in the kernel module.

Kernel fixes and cleanup

---

doc/attr.xml
doc/prop.xml
doc/z-chap4.xml
doc/z-chap5.xml
gap/attr.gd
gap/attr.gi
gap/prop.gd
gap/prop.gi
tst/standard/attr.tst
tst/standard/prop.tst

Implements a new property `IsHamiltonianDigraph` which checks if a given digraph is hamiltonian, and a new attribute `HamiltonianPath` which finds a hamiltonian path if there is one.

Hamiltonian cycles

---

doc/prop.xml
doc/z-chap5.xml
gap/prop.gd
gap/prop.gi
tst/standard/prop.tst

Adds a method "IsChainDigraph" to prop, with related documentation and tests.

Add IsChainDigraph

---

gap/attr.gi
tst/standard/attr.tst
tst/standard/prop.tst

I don't deeply understand the `ArticulationPoints` algorithm, but I changed the one line that looked weird to me, to something that I thought made more sense, and it seems to fix the issue.
Resolves #102.

Fix bug in ArticulationPoints

---

Makefile.am
src/homos.h

Two minor fixes to the build system.

Minor fixes to the build system

---

scripts/travis-build-dependencies.sh

This makes the analogous changes to those that were made to Semigroups in https://github.com/gap-packages/Semigroups/pull/503.

travis: fix issue with cURL

---

PackageInfo.g

This is the same kind of changes that in https://github.com/gap-packages/Semigroups/pull/505

Use full names instead of initials in PackageInfo.g

---

PackageInfo.g
doc/z-title.xml

Since I'm at a different university now, I thought it made sense to adjust my details in PackageInfo.g.

Update Wilf's details in PackageInfo.g

---

src/digraphs.c

Please let me know if I should rebase this on some other branch instead of master (say, stable-0.13 ?)

Various tweaks to the kernel extension

---

.travis.yml
scripts/travis-build-dependencies.sh

Like with https://github.com/gap-packages/Semigroups/pull/557. This makes the Travis setup a little simpler.

Use 'xenial' in Travis rather than 'trusty'

---

doc/grahom.xml
doc/z-chap6.xml
gap/grahom.gd
gap/grahom.gi
tst/standard/grahom.tst

A method that verifies if a list or transformation is a colouring of a digraph. There are no tests or doc for this yet.

Add IsDigraphColouring

---

configure.ac
src/bitarray.h

COUNT_TRUES_BLOCK 

---

.appveyor.yml
.travis.yml
Makefile.am
init.g
scripts/travis-build-dependencies.sh
scripts/travis-build-digraphs.sh
scripts/travis-test.sh

This should hopefully resolve #177.

Fix Digraphs for cygwin

---

tst/standard/grahom.tst

This should get the Travis tests working again in the stable branch, and then the master branch too once stable is merged into master.
Resolves #193.

Temporarily comment out two error-message tests in grahom.tst

---

doc/grahom.xml
src/homos.c
tst/standard/grahom.tst

Resolves Issue #203. @MTWhyte for info.

grahom: allow premature termination in homomorphism search

---

gap/utils.gi

utils: fix DIGRAPHS_Dir

---

gap/attr.gi
tst/standard/attr.tst

This pull request makes a minor tweak to the function `DigraphOddGirth`, avoiding unnecessary computation.

Improve DigraphOddGirth

---

.travis.yml
Makefile.am
configure.ac
m4/ax_check_planarity.m4
scripts/travis-build-dependencies.sh
scripts/travis-build-digraphs.sh
scripts/travis-test.sh
src/planar.c

This PR is similar to:
gap-packages/Semigroups#590
gap-packages/Semigroups#593
gap-packages/Semigroups#595
and partially resolves Issue #205. Thanks to @embray for help with this.

System planarity

---

gap/oper.gi
tst/standard/oper.tst

I think this will fix Issue 213.

Fix issue 213

---

gap/labels.gd
gap/labels.gi
gap/oper.gi
tst/standard/labels.tst
tst/standard/oper.tst

Fix issue 215

---

.travis.yml
Makefile.am
README.md
configure.ac
m4/ax_check_bliss.m4
scripts/travis-build-dependencies.sh
scripts/travis-test.sh
src/digraphs.c
src/homos-graphs.c

cc @james-d-mitchell, @kiwifb, @dimpase

Add --with-external-bliss option to unvendor bliss

---

doc/attr.xml

This pull request updates the documentation in the `attr.xml` file, as discussed [here](https://github.com/gap-packages/Digraphs/projects/1#card-26307115)

Documentation update: attr.xml

---

gap/io.gd
gap/io.gi

I think this "resolves" issue #245

Clean up IO

---

gap/isomorph.gi

Fixes bliss usage message.
The bliss usage message is fixed.

Fix bliss usage message

---

doc/constructors.xml

Update constructors.xml for mutable digraphs

---

doc/oper.xml

Updates the documentation in oper.xml to be true

Update oper.xml for mutable digraphs

---

gap/grahom.gi
tst/standard/grahom.tst

I think this resolves Issue #251

Fix issue 251

---

gap/digraph.gi
gap/oper.gi
tst/standard/oper.tst
tst/testinstall.tst

Fix issue 276: mutability problems in ViewString and DigraphDisjointUnion

---

PackageInfo.g
doc/oper.xml
gap/oper.gd
gap/oper.gi
scripts/travis-build-dependencies.sh
tst/standard/oper.tst

This does the same as #128 with tests and documentation

Add DigraphDijkstraS and DigraphDijkstraST

---

gap/grahom.gd
gap/grahom.gi
tst/standard/grahom.tst

A folding from a multidrgraph to another is a pair of maps (one between the vertex sets and one between the edges sets) which is a digraph homomorphism and with the further property that it induces a bijection between the spaces of bi-infinite paths through the digraphs.
The function takes as input two digraphs and two transformations and checks if the given transformations define a folding.

IsDigraphFolding

---

PackageInfo.g
README.md
doc/main.xml
doc/oper.xml
doc/z-chap1.xml

I forgot to add info about the datastructures package to the manual and the readme for v1.2.0, as pointed out in PR #309 by @wilfwilson. This PR fixes this.

Doc datastructs

---

scripts/travis-build-dependencies.sh
src/bitarray.h
src/cliques.c
src/perms.h
src/planar.c

This PR tries to check the out of bounds error shown by a recent change in GAP, that shows up in the CI:
https://travis-ci.com/github/gap-packages/Digraphs/jobs/399631567

cliques: fix out of bounds error

---

scripts/travis-build-dependencies.sh

I explained roughly what was going wrong https://github.com/digraphs/Digraphs/pull/348#pullrequestreview-532870383.
I'd really appreciate getting this 1-line PR merged ASAP so that the other PRs have proper AppVeyor builds running on them.

Fix AppVeyor integration

---

.codecov.yml

The GitHub actions workflows that I added include Codecov integration. This means that coverage reports get automatically uploaded to Codecov, which we can browse like on here: https://codecov.io/gh/digraphs/Digraphs/branch/stable-1.3
This PR as a configuration file to decide various options for this integration.

Create a .codecov.yml file to configure Codecov

---

ci/coverage.py

I learned that you can pass commands to GAP via the command line option `-c`. This makes the script nicer than piping the commands to GAP. I took the opportunity to make the script a bit nicer overall.

Simplify the code coverage script

---

src/digraphs.c
src/digraphs.h
src/homos.c
tst/testinstall.tst

This PR fixes Issue #367, turns out it pointed out two issues in the homomorphism finding code, and both are fixed in this PR.

Resolve Issue #367

---

README.md
doc/z-chap1.xml

Resolve Issue #320 (Doc config options)

---

.appveyor.yml
.github/workflows/gap.yml

In particular:
* make AppVeyor not build twice when a PR is made from a branch on the same repository.
* Upload the HTML and PDF versions of the Digraphs manuals as an artefact!
This should be useful for checking that everything looks alright with the manual when someone makes a PR that adds or changes documentation.

Update CI setup

---

doc/digraph.xml
gap/digraph.gd
gap/digraph.gi
tst/standard/digraph.tst

This is something else that I've found handy for my research. Since I've written the code, I may as well share it, in case it proves useful to others.

Allow `AsDigraph` to take permutations

---

doc/examples.xml

This pull request fixes an issue in the documentation of the Haar Graph feature.

Haar Graph Documentation Edit

---

doc/examples.xml
doc/z-chap2.xml
gap/examples.gd
gap/examples.gi
tst/standard/examples.tst

This is a continuation of the book digraph. Unlike the book digraph, the stacked book digraph has n as the size of the book spine rather than 2. I also changed the book digraph implementation to use this function. For more information on this graph has a look at https://mathworld.wolfram.com/StackedBookGraph.html.

Add `StackedBookGraph`

---

doc/oper.xml
doc/z-chap4.xml
gap/oper.gd
gap/oper.gi
gap/utils.gd
gap/utils.gi
tst/standard/oper.tst

Adds `IsDigraphPath` missing ~~tests and doc so far~~ nothing.

oper: add IsDigraphPath

---

gap/digraph.gi
tst/testinstall.tst

This PR resolves Issue #517, @wilfwilson is this the fix you envisaged?

digraph: fix String method for chains/cycles

---

PackageInfo.g

This is for his work on random digraphs that was recently merged (PR #531).
Is this the only place we add people?

Add Kamran to PackageInfo.g

---

doc/attr.xml
gap/prop.gd
gap/prop.gi
tst/standard/attr.tst

This PR makes some improvements to my work on lattices, based on the review of #533.
As #538 was based on #533 and merged before it, it seems easiest to close the earlier PR and make all the relevant changes here.

Make improvements to work related to `DIGRAPHS_IsMeetJoinSemilattice`

---

src/cliques.c
src/cliques.h

... as in most other source files in here

Use compiled.h instead of src/compiled.h

---

.mailmap
PackageInfo.g

Update Joe's info

---

etc/code-coverage-test-gap.py
gap/digraph.gi
tst/standard/digraph.tst

@ChrisJefferson hopefully this resolves your issue #645, the previous error message wasn't helpful, I agree!

Improve error message in `DigraphByEdges`

---

gap/weights.gi

- Consistent indenting by 2 instead of 4
- Remove some excessive blank lines
- Adjust some "run-on" lines
Should be non-controversial.

weights.gi: correct whitespace

---

.github/workflows/config_options.yml
.github/workflows/lint.yml
.github/workflows/manual.yml
.github/workflows/os.yml
.github/workflows/ubuntu.yml
.github/workflows/valgrind.yml

New workflow cancels old one

---

etc/code-coverage-test-gap.py

This PR brings the fixes from https://github.com/semigroups/Semigroups/pull/1029 to the Digraphs code coverage script (as they are identical).

Fix code coverage script on certain platforms.

---

PackageInfo.g
init.g

Update to resolve the following issue from GAP
https://github.com/gap-system/gap/issues/5761

Load kernel ext

---

.codespellrc

Adds the word "homs" to the list of ignored words

Update codespell ignored words

---

.mailmap
PackageInfo.g

I am not sure which branch to target with this; let me know and
I can rebase and retarget this PR on something other than `main`.

Update my contact details

---

doc/weights.xml
doc/z-chap5.xml
gap/weights.gd
gap/weights.gi
tst/standard/weights.tst

The next one of @RaiyanC's edge-weighted algorithms, adding randomly generated edge-weighted digraphs.

Edge weights #6: RandomUniqueEdgeWeightedDigraph

---

gap/io.gi
tst/standard/io.tst

This resolves issues #838 and #839, and lets us close #837 which I just made for demonstration purposes.

Fix some issues with `TCodeDecoder`
